services:
  minio:
    image: bitnami/minio:latest
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_API_PORT_NUMBER=10000
      - MINIO_CONSOLE_PORT_NUMBER=10001

volumes:
  minio_data:
