version: '3.8'
services:
  artemis:
    image: apache/activemq-artemis:2.32.0-alpine
    restart: always
    env_file:
      - artemis.env
    environment:
      - ARTEMIS_USER=artemis
      - ANONYMOUS_LOGIN=false
    ports:
      - '61616:61616'
      - '8161:8161'
    volumes: 
      - artemis-data:/var/lib/artemis-instance

volumes:
  artemis-data:
